Implementation;Compile;RootName:HC153
Implementation;Compile||(null)||Please refer to the log file for details about 1 Info(s)||HC153_compile_log.rpt;liberoaction://open_report/file/HC153_compile_log.rpt||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:HC153
Implementation;Synthesis||null||@N: Running in 64-bit mode||HC153.srr(11);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/11||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||HC153.srr(15);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/15||null;null
Implementation;Synthesis|| CG364 ||@N: Synthesizing module HC153 in library work.||HC153.srr(27);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/27||HC153.v(1);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\hdl\HC153.v'/linenumber/1
Implementation;Synthesis||null||@N: Running in 64-bit mode||HC153.srr(39);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/39||null;null
Implementation;Synthesis||null||@N: Running in 64-bit mode||HC153.srr(60);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/60||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||HC153.srr(84);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/84||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||HC153.srr(85);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/85||null;null
Implementation;Synthesis|| BN225 ||@N: Writing default property annotation file D:\chang\_74HC153\synthesis\HC153.sap.||HC153.srr(106);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/106||null;null
Implementation;Synthesis|| MF248 ||@N: Running in 64-bit mode.||HC153.srr(133);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/133||null;null
Implementation;Synthesis|| MF667 ||@N: Clock conversion disabled. (Command "set_option -fix_gated_and_generated_clocks 0" in the project file.)||HC153.srr(134);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/134||null;null
Implementation;Synthesis|| MT320 ||@N: This timing report is an estimate of place and route data. For final timing results, use the FPGA vendor place and route report.||HC153.srr(239);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/239||null;null
Implementation;Synthesis|| MT322 ||@N: Clock constraints include only register-to-register paths associated with each individual clock.||HC153.srr(241);liberoaction://cross_probe/hdl/file/'D:\chang\_74HC153\synthesis\HC153.srr'/linenumber/241||null;null
